Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ${codeuri}
      Handler: hello.handler
      Runtime: python3.11
      RolePath: /foo/bar/
Metadata:
  SamTransformTest: true
